name: maidenhead
description: Maidenhead Locator System in Dart.
version: 0.0.1
homepage: https://github.com/tai-ga/maidenhead

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.18.0

flutter:
