name: gridlocator
description: A library for converting a latitude and longitude into a Maidenhead grid locator.
version: 0.0.5
homepage: https://github.com/tai-ga/gridlocator

environment:
  sdk: '>=3.1.1 <4.0.0'

dev_dependencies:
  lints: any # Ignoring the version to allow editing across SDK versions.
  test: any # Ignoring the version to allow editing across SDK versions.
