name: gridlocator
description: A library for converting a latitude and longitude into a Maidenhead grid locator.
version: 0.0.1
homepage: https://github.com/tai-ga/gridlocator

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.20.0

flutter:
